# Input/output configuration
input_dir: ${EXATRKX_DATA}/embedding_processed/0GeV_cut_testing_2
output_dir: ${EXATRKX_DATA}/filter_processed/0GeV_cut_testing_2
project: CodaFilter0GeV
filter_cut: 0.4
overwrite: True

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 0.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[100, 5, 5]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: True

# Model parameters
in_channels: 12
hidden: 1024
nb_layer: 3
emb_channels: 0
layernorm: True
batchnorm: True
n_chunks: 25
edges_per_batch: 500000
ratio: 2
weight: 2
warmup: 100
lr: 0.01
factor: 0.3
patience: 15
regime: [[ci]]
max_epochs: 30

# Post-processing
callbacks: #[FilterInferenceCallback]
