# Input/output configuration
input_dir: ${EXATRKX_DATA}/embedding_processed/1GeV_cut_testing_1
output_dir: ${EXATRKX_DATA}/filter_processed/1GeV_cut_testing_1
project: CodaFilter1GeV
filter_cut: 0.15
overwrite: True

# Dataset parameters
pt_background_min: 1.0
pt_signal_min: 1.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[450, 25, 25]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: False

# Model parameters
in_channels: 12
hidden: 512
nb_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 8
edges_per_batch: 500000
ratio: 2
weight: 2
warmup: 200
lr: 0.01
factor: 0.3
patience: 20
regime: [[ci]]
max_epochs: 10

# Post-processing
callbacks: #[FilterInferenceCallback]
