# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/feature_store_modulewise_v2
project: ITk_0.5GeV
sanity_steps: 0

# Dataset parameters
pt_signal_min: 500.
pt_background_min: 500.
n_hits: 3
primary_only: True
train_split: [[10, 2, 2]] # Number of [training, validation, testing] examples

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: [512]
nb_layer: 6
emb_dim: 8
weight: 5
randomisation: 1
points_per_batch: 20000
r_train: 1.0
r_val: 1.0
r_test: 1.5
knn: [30]
warmup: 5000
margin: 1
lr: [0.001]
factor: 0.3
patience: 50
regime: [[rp, hnm, ci]]
max_epochs: 50

callbacks: 

