# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/feature_store_modulewise
project: ITk_1GeV

# Dataset parameters
pt_min: 1000
train_split: [[500, 10, 10], [2000, 10, 10]] # Number of [training, validation, testing] examples

# Model parameters
spatial_channels: 3
cell_channels: [2, 4, 8]
emb_hidden: [512, 1024]
nb_layer: [6, 8, 10]
emb_dim: 8
weight: [1, 2, 10]
randomisation: 2
r_train: 1.0
r_val: 1.0
r_test: 1.5
knn: [20, 30, 50]
warmup: 500
margin: 1
lr: 0.001
factor: 0.3
patience: 8
regime: [[rp, hnm, ci]]
max_epochs: 50

callbacks: 

