stage_list:
#     - {set: Processing, name: FeatureStore, config: prepare_feature_store.yaml, batch: configs/batch_cpu_default.yaml}
    - {set: Embedding, name: LayerlessEmbedding, config: train_embedding.yaml, batch_config: configs/batch_gpu_default.yaml}
#     - {set: Filter, name: PyramidFilter, config: train_filter.yaml, batch_config: configs/batch_gpu_default.yaml}
#     - {set: GNN, name: CheckpointedPyramid, config: train_gnn.yaml, batch: configs/batch_gpu_default.yaml}