# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml/feature_store_endcaps_SMALLTEST
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml_processed/embedding_processed/0_pt_cut_endcaps_SMALLTEST
project: EmbeddingStudy
overwrite: True

# Dataset parameters
pt_min: 1
train_split: [[400, 50, 50]] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 5
emb_dim: [10, 12, 16, 24]
weight: 2
randomisation: 2
r_train: 1
r_val: 1
r_test: 1.5
knn: 20
warmup: [400, 1200]
margin: 1
lr: 0.003
factor: 0.3
patience: 5
regime: [[rp, hnm, ci]]
max_epochs: 70

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data