# Input/output configuration
input_dir: ${EXATRKX_DATA}/embedding_processed/PileUp40_LRT
output_dir: ${EXATRKX_DATA}/filter_processed/PileUp40_LRT
project: LRT_mu40_0GeV_Filter
edge_cut: 0.15
overwrite: True

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 0.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[200, 25, 25], [500, 25, 25]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: [512, 1024, 2048]
nb_layer: [3, 4, 6]
emb_channels: 0
layernorm: [False, True]
batchnorm: [False, True]
n_chunks: 12
edges_per_batch: 3000000
ratio: 8
weight: 8
warmup: 200
lr: 0.01
factor: 0.3
patience: 12
regime: [[no_regime]]
max_epochs: 30

# Post-processing
callbacks: [FilterTelemetry]
