# Input/output configuration
input_dir: ${EXATRKX_DATA}/feature_store/all_data
output_dir: ${EXATRKX_DATA}/embedding_processed/0GeV_cut
project: CodaEmbedding0GeV
overwrite: True
sanity_steps: 0

# Dataset parameters
pt_signal_cut: 0.
pt_background_cut: 0.
train_split: [[950, 25, 25]] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: True
nhits: 1
primary_only: False

# Model parameters
spatial_channels: 3
cell_channels: 9
emb_hidden: 1024
nb_layer: 4
emb_dim: 12
activation: Tanh
weight: 5
randomisation: 2
points_per_batch: 100000
r_train: 0.1
r_val: 0.1
r_test: 0.1
knn: 100
warmup: 5
margin: 0.1
lr: 0.001
factor: 0.5
patience: 30
regime: [[rp, hnm, ci, norm]]
max_epochs: 100

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 