name: exatrkx-cpu

channels:
    - defaults
    - pytorch
    - pyg
    - conda-forge

dependencies:
    - numpy
    - pandas
    - scipy
    
    - cpuonly
    - pytorch==1.10.2
    - pytorch-lightning
    - pyg
    - faiss-cpu