name: exatrkx-gpu

channels:
    - rapidsai
    - nvidia
    - pytorch
    - pyg
    - conda-forge
    
dependencies:
    - cudatoolkit=11.3
    - pytorch==1.10.2
    - pytorch-lightning
    - pyg
    - faiss-gpu
    - cudf=21.12
    - cugraph=21.12
    