# Dataset parameters
pt_min: 0.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[1000, 10, 10]] # Number of [training, validation, testing] examples
endcaps: True

# Model parameters
in_channels: 3
hidden: [64, 96, 128]
factor: 0.3
patience: 50
regime: [[non_ci, pid]]
max_epochs: 200
slack_alert: False
stage:
    resume_id: 123
    set: GNN

# Post-processing
callbacks:  #[GNNInferenceCallback]
