# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/filter_processed/0.5GeV_testing
project: ITk_0.5GeV_GNN

# Dataset parameters
pt_background_min: 1000.
pt_signal_min: 1000.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[25, 25, 25]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: False

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 8
hidden: 64
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 2
warmup: 500
lr: 0.001
factor: 0.3
patience: 20
regime: [[pid, ci]]
max_epochs: 2

# Post-processing
callbacks: #[GNNInferenceCallback]