# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/filter_processed/0.5GeV_testing
project: ITk_0.5GeV_GNN

# Dataset parameters
pt_background_min: 500.
pt_signal_min: 500.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[1000, 25, 25]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: False

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 0
hidden: 96
n_graph_iters: 8
nb_node_layer: [2, 3]
nb_edge_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: Mish
weight: 2
warmup: 500
lr: 0.002
factor: 0.3
patience: 30
regime: [[pid]]
max_epochs: 50

# Post-processing
callbacks: #[GNNInferenceCallback]