# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/trackml-codalab/feature_store/all_data

# Dataset parameters
pt_signal_cut: 0.
pt_background_cut: 0.
train_split: [400, 10, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: True
nhits: 1
primary_only: False

# Model parameters
spatial_channels: 3
cell_channels: 9
emb_hidden: 1024
nb_layer: 4
emb_dim: 10
activation: Tanh
weight: 3
randomisation: 2
points_per_batch: 200000
r_train: 0.1
r_val: 0.1
r_test: 0.1
knn: 100
warmup: 5
margin: 0.1
lr: 0.001
factor: 0.7
patience: 30
regime: [rp, hnm, ci, norm]
max_epochs: 50

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
