# Input/output configuration
input_dir: /global/project/projectdirs/m3443/usr/vsreenivasan/embedding_processed_updated/results/
output_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/filter_processed/1_GeV_unweighted
project: ITk_1GeV_Filter
filter_cut: 0.15

# Dataset parameters
pt_min: 0
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [50, 10, 10] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
hidden: 512
nb_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 12
ratio: 2
weight: 2
warmup: 50
lr: 0.01
factor: 0.3
patience: 8
regime: [ci]
max_epochs: 20

# Post-processing
callbacks: [] #[FilterInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data