# Input/output configuration
input_dir: /project/projectdirs/m3443/data/trackml-codalab/feature_store/testing_1

# Dataset parameters
pt_signal_min: 1.
pt_background_min: 1.
train_split: [80, 10, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 4
emb_dim: 8
weight: 10
randomisation: 2
points_per_batch: 100000
r_train: 1.0
r_val: 1.0
r_test: 1.0
knn: 50
warmup: 30
margin: 1
lr: 0.0001
factor: 0.3
patience: 15
regime: [rp, hnm, ci]
max_epochs: 50

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
