libraries:
    model_library: /global/homes/d/danieltm/ExaTrkX/Tracking-ML-Exa.TrkX/src/Pipelines/Examples/LightningModules
    artifact_library: /global/cscratch1/sd/danieltm/ExaTrkX/lightning_checkpoints

stage_list:
#     - {set: Processing, name: FeatureStore, config: prepare_small_feature_store.yaml, resume_id: }
    - {set: Embedding, name: LayerlessEmbedding, config: train_small_embedding.yaml, resume_id: }