libraries:
    model_library: /global/homes/d/danieltm/ExaTrkX/Tracking-ML-Exa.TrkX/src/Pipelines/Examples/LightningModules
    artifact_library: /global/cscratch1/sd/danieltm/ExaTrkX/lightning_checkpoints

stage_list:
    - {set: Processing, name: FeatureStore, config: prepare_coda_small_feature_store.yaml, resume_id: }
#     - {set: Embedding, name: LayerlessEmbedding, config: train_coda_small_embedding.yaml, resume_id: pbn07koj, override: {
#     input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/feature_store_endcaps_all,
#     output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/0_pt_cut_endcaps_unweighted_all,
#     r_test: 1.85, overwrite: False, callbacks: EmbeddingInferenceCallback, train_split: [[7000, 250, 250]]}}
#     - {set: Embedding, name: LayerlessEmbedding, config: train_coda_small_embedding.yaml, resume_id: suvpgvg8, override: {
#     input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/feature_store_endcaps_all,
#     output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/0_pt_cut_endcaps_weighted_all,
#     r_test: 1.95, overwrite: False, callbacks: EmbeddingInferenceCallback, max_epochs: 96, train_split: [[7000, 250, 250]]}}
#     - {set: Filter, name: VanillaFilter, config: train_coda_filter.yaml, resume_id: eqzrkf4q, override: {filter_cut: 0.029,
#     input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/0_pt_cut_endcaps_unweighted_all, output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/filter_processed/0_pt_cut_endcaps_unweighted_all, 
#     overwrite: False, max_epochs: 49, callbacks: FilterInferenceCallback, datatype_split: [[7000, 250, 250]]}}
#     - {set: Filter, name: VanillaFilter, config: train_coda_filter.yaml, resume_id: 4vvq72tn, override: {filter_cut: 0.0253,
#     input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/0_pt_cut_endcaps_weighted_all, output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/filter_processed/0_pt_cut_endcaps_weighted_all, 
#     overwrite: False, max_epochs: 59, callbacks: FilterInferenceCallback, datatype_split: [[7000, 250, 250]]}}
#     - {set: GNN, name: SliceCheckpointedResAGNN, config: train_coda_gnn.yaml, resume_id: }
    