stage_list:
    - {set: Processing, name: TrackMLFeatureStore, config: prepare_quickstart.yaml, batch_config: batch_cpu_default.yaml}
    - {set: Embedding, name: LayerlessEmbedding, config: train_quickstart_embedding.yaml, batch_config: batch_gpu_default.yaml, resume_id: 1srsexda}