# Input/output configuration
input_dir: ${ITK_DATA}/filter_processed/0GeV_barrel_v3
project: ITk_1GeV_Barrel_GNN

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 1000.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[100, 25, 25]] # Number of [training, validation, testing] examples
endcaps: False
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 8
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
batchnorm: True
aggregation: sum_max
hidden_activation: ReLU
weight: 2
warmup: 3
lr: 0.0001
factor: 0.3
patience: 20
regime: [[pid]]
max_epochs: 2

# Post-processing
callbacks: #[GNNInferenceCallback]