# Location of libraries
libraries:
    model_library: ${EXATRKX_PIPELINE}/LightningModules
    artifact_library: ${EXATRKX_DATA}/lightning_checkpoints

# The lines you would like/need in a batch script before the call to pipeline.py
custom_batch_script:
    - bash
    - conda activate exatrkx-test
    
# Which logger to use - options are Weights & Biases [wandb], TensorBoard [tb], or [None]
logger: tb