# Input/output configuration
input_dir: ${ITK_DATA}/feature_store/feature_store_modulewise_barrel
output_dir: ${ITK_DATA}/embedding_processed/0.5GeV_barrel
project: ITk_0.5GeV_Barrel_Embedding
overwrite: True
sanity_steps: 0

# Dataset parameters
pt_signal_cut: 500.
pt_background_cut: 500.
nhits: 3
primary_only: True
train_split: [[500, 25, 25]] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: 1946
nb_layer: 5
emb_dim: 8
weight: 30
randomisation: 2
points_per_batch: 100000
r_train: 1.0
r_val: 1.0
r_test: 1.0
knn: 85
warmup: 900
margin: 1
lr: 0.001
factor: 0.9
patience: 1
regime: [[rp, hnm, ci]]
max_epochs: 40

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 