# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml_processed/filter_processed/0_pt_cut_endcaps_connected_high_eff
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml_processed/gnn_processed/0_pt_cut_endcaps_connected
project: GNNComparisons
edge_cut: 0.5

# Dataset parameters
pt_min: 1.0
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [100, 10, 10] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
hidden: 128
n_graph_iters: 8
nb_node_layer: 2
nb_edge_layer: 2
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 2
delta_eta: 0.8
warmup: 100
lr: 0.001
factor: 0.3
patience: 30
regime:
    - non_ci # This is to NOT include cell information. Switch comment with "ci" to include cell information
#     - ci
    - pid
max_epochs: 1
slack_alert: False

# Post-processing
callbacks: [GNNTelemetry]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
