# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/embedding_processed/0GeV_barrel
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/filter_processed/0GeV_barrel
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_1GeVSignal_Barrel_Filter
edge_cut: 0.5

# Dataset parameters
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [1000, 20, 5] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges

# Model parameters
spatial_channels: 3
cell_channels: 8
hidden: 1024
nb_layer: 4
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 4
edges_per_batch: 1000000
ratio: 8
weight: 8
# val_subset: 0.1
warmup: 1000
lr: 0.002
factor: 0.3
patience: 40
regime: [ci]
max_epochs: 100
