# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/LRT/v3/pileup40_train/embedding_processed_Pyg2
output_dir: /global/cfs/cdirs/m3443/data/LRT/v3/pileup40_train/filter_processed_Pyg2
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: LRT_mu40_1GeV_Filter
model: PyramidFilter
edge_cut: 0.2
gpus: 4
nodes: 1

# Dataset parameters
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [1000, 10, 1] # Number of [training, validation, testing] examples
true_edges: layerless_true_edges

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: 1024
nb_layer: 4
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 2
edges_per_batch: 300000
ratio: 8
weight: 8
warmup: 10
lr: 0.02
factor: 0.7
patience: 20
regime: []
max_epochs: 500
