# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/embedding_processed/0_GeV_unweighted_subset
output_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/filter_processed/0_GeV_unweighted_subset
project: ITk_0GeV_Filter
filter_cut: 0.2

# Dataset parameters
pt_background_min: 1.0
pt_signal_min: 1.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[25, 5, 1], [100, 5, 1]] # Number of [training, validation, testing] examples
endcaps: True
endcaps: True
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 8
hidden: [512, 1024]
nb_layer: [3, 6]
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 80
edges_per_batch: [300000, 500000]
ratio: [1, 2, 4, 8]
weight: 2
warmup: 100
lr: [0.001, 0.01]
factor: 0.3
patience: 20
regime: [[ci]]
max_epochs: 50

# Post-processing
callbacks: #[FilterInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
