# Input/output configuration
input_dir: ${EXATRKX_DATA}/filter_processed/1GeV_cut_testing_1
output_dir: ${EXATRKX_DATA}/gnn_processed/1GeV_cut_testing_1
project: CodaGNN1GeV
edge_cut: 0.5
overwrite: True

# Dataset parameters
pt_background_min: 1.0
pt_signal_min: 1.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[450, 50, 50]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: False

# Model parameters
in_channels: 3
hidden: 64
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 2
delta_eta: 1.2
warmup: 450
lr: 0.001
factor: 0.3
patience: 20
regime: [[pid]]
max_epochs: 50
slack_alert: False

# Post-processing
callbacks:  #[GNNInferenceCallback]
