# Input/output configuration
input_dir: ${EXATRKX_DATA}/filter_processed/0GeV_cut_testing_2
output_dir: ${EXATRKX_DATA}/gnn_processed/0GeV_cut_testing_2
project: CodaGNN0.5GeV
edge_cut: 0.5
overwrite: True

# Dataset parameters
pt_background_min: 0.5
pt_signal_min: 0.5
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[450, 50, 50], [1500, 50, 50]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: True

# Model parameters
in_channels: 3
hidden: 64
n_graph_iters: 8
nb_node_layer: [2, 3]
nb_edge_layer: 3
emb_channels: 0
layernorm: [False, True]
hidden_activation: ReLU
weight: 2
warmup: 450
lr: [0.002, 0.001, 0.0005]
factor: 0.3
patience: 20
regime: [[pid]]
max_epochs: 50
slack_alert: False

# Post-processing
callbacks:  #[GNNInferenceCallback]
