input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/filter_processed/0GeV_v3
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_v3
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_1GeVSignal_GNN
model: InteractionGNN
gpus: 4
nodes: 4

# Dataset parameters
pt_background_cut: 0.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [4000, 80, 10] # Number of [training, validation, testing] examples
sorted_events: False
endcaps: True
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 0
hidden: 128
n_graph_iters: 8
nb_node_layer: 2
nb_edge_layer: 2
emb_channels: 0
layernorm: True
batchnorm: False
aggregation: sum
hidden_activation: SiLU
output_activation: Tanh
weight: 10
warmup: 5
lr: 0.001
factor: 0.9
train_purity: 0
patience: 15
truth_key: pid_signal
mask_background: True
max_epochs: 200