# Dataset
program: train.py
method: bayes
project: ITk_1GeVSignal_Barrel_GNN
metric:
    name: sig_fake_ratio.max
    goal: maximize
parameters:
    # Model hyperparameters
    nb_graph_iters:
        min: 4
        max: 10
    hidden:
        min: 32
        max: 512
    layer_norm:
        values: [False, True]
    regime:
        values: [[y], [y_pid], [y-y_pid]]
    cell_channels:
        values: [0, 4, 11]
        
    # Training hyperparameters
    lr: 
        min: 0.00001
        max: 0.05
    patience: 
        min: 1
        max: 25
    factor: 
        min: 0.1
        max: 0.9
    weight:
        min: 4
        max: 20

early_terminate:
    type: hyperband
    min_iter: 3