# Dataset
program: train.py
method: bayes
project: ITk_1GeVSignal_Barrel_GNN
metric:
    name: custom_f1.max
    goal: maximize
    
parameters:
    # Model hyperparameters
    hidden:
        min: 32
        max: 512
    batchnorm:
        values: [True, False]
    model:
        values: [InteractionGNN, CheckpointedPyramid]
    regime:
        values: [[y], [y_pid], [y-y_pid]]
    datatype_split:
        values: [[500, 50, 10], [1000, 50, 10]]
        
    # Training hyperparameters
    lr: 
        min: 0.00001
        max: 0.05
    patience: 
        min: 1
        max: 50
    factor: 
        min: 0.1
        max: 0.9
    weight:
        min: 2
        max: 20

early_terminate:
    type: hyperband
    min_iter: 3