name: exatrkx-hsf2

channels:
    - pytorch
    - pyg
    - conda-forge

dependencies:
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
    - cudatoolkit=11.3
    - pytorch==1.11
    - pytorch-lightning
    - pyg
    