# Input/output configuration
input_dir: /mnt/c/Users/Daniel/Dropbox/Research/Publications/ExaTrkX/trackml/embedding_output/run1
output_dir: /mnt/c/Users/Daniel/Dropbox/Research/Publications/ExaTrkX/trackml/filter_output/run1
project: FilteringStudy

# Dataset parameters
pt_min: 0
train_split: [60, 20, 20] # Number of [training, validation, testing] examples
endcaps: False
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
hidden: 512
nb_layer: 3
emb_channels: 0
layernorm: False
batchnorm: False
weight: 8
ratio: 8
val_subset: 0.1
warmup: 100
lr: 0.002
factor: 0.3
patience: 5
regime:
  # - non_ci # This is to NOT include cell information. Switch comment with "ci" to include cell information
  - ci
    # - pid
max_epochs: 100
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
