# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/feature_store_modulewise
project: ITk_1GeV

# Dataset parameters
pt_min: 1000
train_split: [500, 10, 10] # Number of [training, validation, testing] examples

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: 512
nb_layer: 6
emb_dim: 8
weight: 2
randomisation: 2
r_train: 1.0
r_val: 1.0
r_test: 1.5
knn: 30
warmup: 1000
margin: 1
lr: 0.001
factor: 0.3
patience: 8
regime: [rp, ci, hnm]
max_epochs: 10

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
