# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_all_v3
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_EmbeddingSandbox_C

# Dataset parameters
pt_signal_cut: 1000.
pt_background_cut: 1000.
nhits: 3.
primary_only: True
train_split: [100, 5, 1] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 11
emb_hidden: 1024
nb_layer: 4
emb_dim: 12
activation: Tanh
randomisation: 1
points_per_batch: 100000
output_k: 10
output_r: 0.1
output_weight: 4
output_margin: 0.1

latent_k: 10
latent_r: 0.1
latent_margin: 0.1
latent_weight: 2

warmup: 10
lr: 0.004
factor: 0.7
scheduler: step
patience: 10
regime: [rp, ci, hnm, norm]
working_points: [99, 98, 95] # Need to list in decreasing efficiency
max_epochs: 50