common_configs:
  experiment_name: trackml_quickstart_1
  artifact_directory: artifacts
  gpus: -1

metric_learning_configs:
  # Training parameters
  # num_nodes: 1
  loggers: [CSVLogger]

  # Dataset parameters
  input_dir: datasets/full_data
  output_dir: datasets/quickstart_metric_learning_processed
  pt_signal_cut: 1.
  pt_background_cut: 0.
  # train_split: [7000, 50, 50] # Number of [training, validation, testing] examples
  train_split: [95, 2.5, 2.5]
  n_events: 100
  true_edges: modulewise_true_edges
  n_examples: 100

  # Model parameters
  spatial_channels: 3
  cell_channels: 9
  emb_hidden: 1024
  nb_layer: 4
  emb_dim: 12
  activation: Tanh
  weight: 1
  randomisation: 2
  points_per_batch: 100000
  r_train: 0.1
  r_val: 0.1
  r_test: 0.1
  knn: 50
  warmup: 10
  margin: 0.1
  lr: 0.001
  min_lr: 0.0002
  factor: 0.9
  patience: 1
  regime: [rp, hnm, norm]
  max_epochs: 100

filter_configs:
  input_dir: /global/project/projectdirs/m3443/usr/vsreenivasan/embedding_processed_updated/results/
  output_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/filter_processed/1_GeV_unweighted
  project: ITk_1GeV_Filter
  filter_cut: 0.15

  # Dataset parameters
  pt_min: 0
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [50, 10, 10] # Number of [training, validation, testing] examples
  endcaps: True
  layerwise: False
  layerless: True
  noise: False
  adjacent: False

  # Model parameters
  in_channels: 12
  hidden: 512
  nb_layer: 3
  emb_channels: 0
  layernorm: True
  batchnorm: False
  n_chunks: 12
  ratio: 2
  weight: 2
  warmup: 50
  lr: 0.01
  factor: 0.3
  patience: 8
  regime: [ci]
  max_epochs: 20

  # Post-processing
  callbacks: [] #[FilterInferenceCallback]

  # Logging
  wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data


gnn_configs:
  # Dataset parameters
  input_dir: datasets/quickstart_metric_learning_processed
  output_dir: datasets/quickstart_gnn_processed
  edge_cut: 0.5
  pt_signal_min: 1.
  pt_background_min: 1.
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [80, 10, 10] # Number of [training, validation, testing] examples
  noise: False

  # Model parameters
  spatial_channels: 3
  cell_channels: 8
  hidden: 128
  n_graph_iters: 8
  nb_node_layer: 3
  nb_edge_layer: 3
  layernorm: True
  aggregation: sum_max
  hidden_activation: SiLU
  weight: 2
  warmup: 5
  lr: 0.001
  factor: 0.3
  patience: 10
  truth_key: pid_signal
  regime: [[pid]]
  mask_background: True
  max_epochs: 20


track_building_configs:
  score_cut: 0.8
  output_dir: datasets/quickstart_track_building_processed

evaluation_configs:
  output_dir: datasets/quickstart_evaluation
  min_pt: 1
  max_eta: 4
  matching_fraction: 0.5
