input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/filter_processed/0GeV_barrel
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_barrel
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_Stitcher_Testing
model: CheckpointedPyramid
gpus: 4

# Dataset parameters
pt_background_cut: 0.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [1900, 50, 10] # Number of [training, validation, testing] examples
endcaps: False
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 11
hidden: 309
n_graph_iters: 5
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: False
batchnorm: False
aggregation: mean_max
hidden_activation: SiLU
weight: 5
warmup: 1000
lr: 0.004
factor: 0.5
patience: 20
regime: []
max_epochs: 50