input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/filter_processed/0GeV_barrel
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_barrel
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_Stitcher_Testing
model: CheckpointedPyramid

# Dataset parameters
pt_background_cut: 0.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [500, 50, 10] # Number of [training, validation, testing] examples
endcaps: False
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 8
hidden: 256
n_graph_iters: 4
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
aggregation: mean_max
hidden_activation: SiLU
weight: 100
warmup: 500
lr: 0.001
factor: 0.7
patience: 20
regime: []
max_epochs: 50