# Dataset
program: train.py
method: bayes
project: ITk_Stitcher_Testing
metric:
    name: auc.max
    goal: maximize
parameters:
    # Model hyperparameters
    nb_graph_iters:
        min: 4
        max: 10
    hidden:
        min: 32
        max: 512
    layer_norm:
        values: [False, True]
    cell_channels:
        values: [0, 4, 11]
    datatype_split:
        values: [[500, 50, 10], [1000, 50, 10]]
    model:
        values: [CheckpointedPyramid, InteractionGNN]
        
    # Training hyperparameters
    lr: 
        min: 0.00001
        max: 0.004
    patience: 
        min: 1
        max: 25
    factor: 
        min: 0.1
        max: 0.9
    weight:
        min: 5
        max: 100