# Input/output configuration
input_dir: /project/projectdirs/m3443/data/trackml-codalab/feature_store_endcaps_SMALLTEST

# Dataset parameters
pt_min: 1
train_split: [10, 20, 20] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
emb_hidden: 64
nb_layer: 4
emb_dim: 8
weight: 2
randomisation: 2
r_train: 1
r_val: 1
r_test: 1.5
knn: 50
warmup: 300
margin: 1
lr: 0.002
factor: 0.3
patience: 8
regime: [rp, hnm, ci]
max_epochs: 10

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data