# Input/output configuration
input_dir: ${EXATRKX_DATA}/feature_store/testing_2
output_dir: ${EXATRKX_DATA}/embedding_processed/0GeV_cut_testing_2
project: CodaEmbedding0GeV
overwrite: True

# Dataset parameters
pt_signal_min: 0.
pt_background_min: 0.
train_split: [[950, 25, 25]] # Number of [training, validation, testing] examples
true_edges: layerwise_true_edges
noise: True

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 4
emb_dim: 8
weight: 10
randomisation: 2
points_per_batch: 100000
r_train: 1.0
r_val: 1.0
r_test: 1.5
knn: 50
warmup: 80
margin: 1
lr: 0.001
factor: 0.3
patience: 10
regime: [[rp, hnm, ci]]
max_epochs: 20

# Postprocessing
callbacks: EmbeddingTelemetry