# Input/output configuration
input_dir: ${EXATRKX_DATA}/feature_store/testing_1
output_dir: ${EXATRKX_DATA}/embedding_processed/1GeV_cut_testing_1
project: CodaEmbedding1GeV
overwrite: True

# Dataset parameters
pt_signal_min: 1.
pt_background_min: 1.
train_split: [[450, 25, 25]] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 4
emb_dim: 8
weight: 10
randomisation: 2
points_per_batch: 100000
r_train: 1.0
r_val: 1.0
r_test: 1.5
knn: 50
warmup: 80
margin: 1
lr: 0.001
factor: 0.3
patience: 10
regime: [[rp, hnm, ci]]
max_epochs: 10

# Postprocessing
callbacks: 