# Input/output configuration
input_dir: ${EXATRKX_DATA}/feature_store/quickstart_example
output_dir: ${EXATRKX_DATA}/embedding_processed/1_pt_cut_quickstart_example
project: CodaEmbeddingStudy
overwrite: True

# Dataset parameters
pt_min: 1.0
train_split: [[10, 2, 2]] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 6
emb_dim: 8
weight: 1
randomisation: 2
r_train: 1
r_val: 1
r_test: 1.5
knn: 20
warmup: 1600
margin: 1
lr: 0.002
factor: 0.3
patience: 8
regime: [[rp, hnm, ci]]
max_epochs: 1

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 