# Input/output configuration
input_dir: ${EXATRKX_DATA}/feature_store/quickstart_example
output_dir: ${EXATRKX_DATA}/embedding_processed/1GeV_pt_cut_quickstart_example
project: CodaEmbeddingStudy
overwrite: True

# Dataset parameters
pt_signal_cut: 1.0
pt_background_cut: 1.0
train_split: [[300, 20, 20]] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: 1024
nb_layer: 4
emb_dim: 12
weight: 2
activation: Tanh
randomisation: 2
points_per_batch: 100000
r_train: 0.1
r_val: 0.1
r_test: 0.1
knn: 100
warmup: 3
margin: 0.1
lr: 0.0001
factor: 0.3
patience: 10
regime: [[rp, ci, hnm, norm]]
max_epochs: 30

# Postprocessing
callbacks: [[EmbeddingTelemetry, EmbeddingBuilder]]