# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/feature_store_endcaps_SMALLTEST
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/0_pt_cut_endcaps_weighted
project: CodaEmbeddingStudy
overwrite: True

# Dataset parameters
pt_min: 0
train_split: [[100, 20, 20]] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 6
emb_dim: 8
weight: 1
randomisation: 2
r_train: 1
r_val: 1
r_test: 1.5
knn: 20
warmup: 1600
margin: 1
lr: 0.002
factor: 0.3
patience: 8
regime: [[weighting, rp, hnm, ci]]
max_epochs: 10

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data