input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/filter_processed/0GeV_v3
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_v3
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_1GeVSignal_GNN
model: InteractionGNN

# Dataset parameters
pt_background_cut: 0.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 20, 10] # Number of [training, validation, testing] examples
sorted_events: False
endcaps: True
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 0
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
batchnorm: True
aggregation: mean_max
hidden_activation: SiLU
weight: 5
warmup: 3
lr: 0.002
factor: 0.7
train_purity: 0
patience: 20
truth_key: pid_signal
mask_background: False
max_epochs: 50