# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_barrel
artifacts: /global/cscratch1/sd/danieltm/ExaTrkX/lightning_checkpoints/
project: ITk_DirectedHalfTwin


# Dataset parameters
pt_signal_cut: 500.
pt_background_cut: 500.
nhits: 3.
primary_only: True
train_split: [100, 25, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: 1024
nb_layer: 4
emb_dim: 8
weight: 2
randomisation: 10
points_per_batch: 100000
r_train: 0.2
r_val: 0.2
r_test: 1.5
knn: 100
warmup: 2000
margin: 1
lr: 0.002
factor: 0.9
patience: 1
regime: [rp, ci, hnm]
max_epochs: 50

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
