input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_barrel_v3
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_redux_processed/0GeV_barrel_v3
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_1GeVSignal_Barrel_GNNRedux
model: InteractionGNN
input_cut: 0.1

# Dataset parameters
pt_background_cut: 0.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [100, 20, 10] # Number of [training, validation, testing] examples
sorted_events: False
endcaps: False
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 11
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: False
batchnorm: False
aggregation: mean_sum
hidden_activation: SiLU
weight: 2
warmup: 3
lr: 0.0001
factor: 0.7
train_purity: 0
patience: 20
truth_key: pid_signal
mask_background: True
max_epochs: 50