# Input/output configuration
input_dir: ${EXATRKX_DATA}/train_all
output_dir: ${EXATRKX_DATA}/feature_store/testing_2
detector_path: ${EXATRKX_DATA}/detectors.csv
n_files: 3000
n_workers: 
n_tasks: 1
overwrite: False

endcaps: True
noise: True
layerwise: True
modulewise: True
cell_information: True
