common_configs:
  experiment_name: trackml
  artifact_directory: /pscratch/sd/p/pmtuan/artifacts
  gpus: -1
  wandb_project: 'TrackML'
  clear_directories: true

gnn_configs:
  # Dataset parameters
  input_dir: datasets/filter_processed
  output_dir: datasets/gnn_processed_trackml
  edge_cut: 0.5
  pt_signal_min: 1.
  pt_background_min: 0.
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [80, 10, 10] # Number of [training, validation, testing] examples
  n_events: 1000
  noise: False

  # Model parameters
  spatial_channels: 3
  cell_channels: 8
  hidden: 128
  n_graph_iters: 8
  nb_node_layer: 3
  nb_edge_layer: 3
  layernorm: True
  aggregation: sum_max
  hidden_activation: SiLU
  weight: 3
  warmup: 0
  lr: 0.005
  factor: 0.9
  patience: 20
  min_lr: 0.0001
  truth_key: pid_signal
  regime: [[pid]]
  mask_background: True
  max_epochs: 1000

  loggers: 
    - CSVLogger
    - WandbLogger


track_building_configs:
  score_cut: 0.8
  output_dir: datasets/quickstart_track_building_processed

evaluation_configs:
  output_dir: datasets/trackml_evaluation
  min_pt: 1
  max_eta: 4
  matching_fraction: 0.5
  min_particle_length: 3
  matching_fraction: 0.5
  matching_style: ATLAS
  min_track_length: 3
