# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/trackml-codalab/feature_store/quickstart_example_1GeV

# Dataset parameters
pt_signal_cut: 1.
pt_background_cut: 1.
train_split: [80, 10, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 9
emb_hidden: 1024
nb_layer: 4
emb_dim: 12
activation: Tanh
weight: 1
randomisation: 1
points_per_batch: 100000
r_train: 0.1
r_val: 0.1
r_test: 0.1
knn: 100
warmup: 5
margin: 0.1
lr: 0.001
factor: 0.5
patience: 30
regime: [rp, hnm, ci, norm]
max_epochs: 50

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
