# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_all
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_0GeV_Denoising


# Dataset parameters
pt_signal_cut: 1000.
pt_background_cut: 0.
nhits: 3.
primary_only: True
train_split: [1000, 25, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: True
cut: 0.5

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: 1024
nb_layer: 6
activation: Tanh
weight: 4
randomisation: 2
points_per_batch: 200000
warmup: 1000
lr: 0.001
factor: 0.3
patience: 30
regime: [ci]
max_epochs: 50

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
