# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/embedding_processed/0.5GeV_barrel
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/filter_processed/0.5GeV_barrel
artifacts: /global/cscratch1/sd/danieltm/ExaTrkX/lightning_checkpoints/
project: ITk_0.5GeV_Barrel_Filter
edge_cut: 0.3

# Dataset parameters
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 20, 20] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges

# Model parameters
spatial_channels: 3
cell_channels: 8
hidden: 1024
nb_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 4
edges_per_batch: 1000000
ratio: 1
weight: 3
# val_subset: 0.1
warmup: 600
lr: 0.002
factor: 0.3
patience: 40
regime: [ci]
max_epochs: 50
