# Input/output configuration
input_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/embedding_processed/0.5GeV_testing
output_dir: /project/projectdirs/m3443/data/ITk-upgrade/processed/filter_processed/0.5GeV_testing
project: ITk_1GeV_Filter
filter_cut: 0.15

# Dataset parameters
pt_min: 0
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [1, 1, 1] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
spatial_channels: 3
cell_channels: 8
hidden: 1024
nb_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 1
edges_per_batch: 50000
ratio: 1
weight: 2
# val_subset: 0.1
warmup: 200
lr: 0.001
factor: 0.3
patience: 20
regime: [ci]
max_epochs: 50

# Post-processing
callbacks: [] #[FilterInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data