# Input/output configuration
input_dir: /project/projectdirs/m3443/data/trackml-codalab/embedding_processed/PileUp40_LRT
output_dir: /project/projectdirs/m3443/data/trackml-codalab/filter_processed/PileUp40_LRT
project: LRT_mu40_0GeV_Filter
edge_cut: 0.15

# Dataset parameters
pt_min: 0
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 10, 10] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: 1024
nb_layer: 4
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 12
edges_per_batch: 3000000
ratio: 8
weight: 8
warmup: 50
lr: 0.01
factor: 0.3
patience: 12
regime: []
max_epochs: 20

# Post-processing
callbacks: [] #[FilterInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data