# Input/output configuration
input_dir: /project/projectdirs/m3443/data/trackml-codalab/filter_processed/PileUp40_LRT
output_dir: /project/projectdirs/m3443/data/trackml-codalab/gnn_processed/PileUp40_LRT

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 0.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 25, 1] # Number of [training, validation, testing] examples
endcaps: True
true_edges: modulewise_true_edges
noise: False
train_purity: 0.

# Model parameters
edge_cut: 0.5
spatial_channels: 3
cell_channels: 0
hidden: 48
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
aggregation: "sum_max"
hidden_activation: SiLU
weight: 5
warmup: 500
lr: 0.005
factor: 0.3
patience: 20
regime: [pid]
max_epochs: 50