common_configs:
  experiment_name: itk
  artifact_directory: /pscratch/sd/p/pmtuan/artifacts
  gpus: -1
  wandb_project: 'Itk'

metric_learning_configs:
  loggers: 
    # - CSVLogger
    - TensorBoardLogger
    - WandbLogger

  # Dataset parameters
  input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_barrel_v3
  output_dir: datasets/metric_learning_processed_itk
  pt_signal_cut: 1000.
  pt_background_cut: 0.
  # train_split: [7000, 50, 50] # Number of [training, validation, testing] examples
  train_split: [90, 5, 5]
  true_edges: modulewise_true_edges
  n_events: 400
  n_inference_events: 1000
  noise: false

  # Model parameters
  spatial_channels: 3
  cell_channels: 11
  emb_hidden: 1024
  nb_layer: 4
  emb_dim: 12
  activation: Tanh
  weight: 1
  randomisation: 2
  points_per_batch: 100000
  r_train: 0.1
  r_val: 0.1
  r_test: 0.1
  knn: 100
  warmup: 50
  margin: 0.1
  lr: 0.001
  min_lr: 0.0002
  factor: 0.9
  patience: 20
  regime: [rp, hnm, norm]
  max_epochs: 400

filter_configs:
  input_dir: datasets/metric_learning_processed
  output_dir: datasets/filter_processed
  project: Itk
  filter_cut: 0.15
  edge_cut: 0.2
  overwrite: True

  # Dataset parameters
  pt_background_min: 0.
  pt_signal_min: 0.
  pt_min: 0
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [90, 5, 5] # Number of [training, validation, testing] examples
  n_events: 100
  endcaps: True
  true_edges: modulewise_true_edges
  layerwise: False
  layerless: True
  noise: False
  adjacent: False

  # Model parameters
  spatial_channels: 3
  cell_channels: 8
  in_channels: 12
  hidden: 512
  nb_layer: 3
  emb_channels: 12
  layernorm: True
  batchnorm: False
  n_chunks: 8
  edges_per_batch: 500000
  ratio: 4
  weight: 4
  warmup: 50
  lr: 0.001
  min_lr: 0.0002
  factor: 0.3
  patience: 20
  regime: [ci]
  max_epochs: 400

  # Post-processing
  callbacks: [] #[FilterInferenceCallback]

  # Logging
  wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
  loggers:
   - CSVLogger
  #  - WandbLogger

gnn_configs:
  # Dataset parameters
  input_dir: datasets/quickstart_metric_learning_processed
  output_dir: datasets/quickstart_gnn_processed
  edge_cut: 0.5
  pt_signal_min: 1.
  pt_background_min: 1.
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [80, 10, 10] # Number of [training, validation, testing] examples
  noise: False

  # Model parameters
  spatial_channels: 3
  cell_channels: 8
  hidden: 128
  n_graph_iters: 8
  nb_node_layer: 3
  nb_edge_layer: 3
  layernorm: True
  aggregation: sum_max
  hidden_activation: SiLU
  weight: 2
  warmup: 5
  lr: 0.001
  factor: 0.3
  patience: 10
  truth_key: pid_signal
  regime: [[pid]]
  mask_background: True
  max_epochs: 20


track_building_configs:
  score_cut: 0.8
  output_dir: datasets/quickstart_track_building_processed

evaluation_configs:
  output_dir: datasets/quickstart_evaluation
  min_pt: 1
  max_eta: 4
  matching_fraction: 0.5
