name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge   
          activate-environment: exatrkx-cpu
#           environment-file: cpu_environment.yml
      - name: Install libraries
        run: mamba env update -n exatrkx-cpu -f cpu_environment.yml
#       - name: Activate environment
#         run: $CONDA/bin/activate exatrkx-cpu
#       - name: Setup libraries
#         run: pip install -e .
      - name: Test Import
        run: python -c 'from Pipelines.TrackML_Example.LightningModules.Embedding.embedding_base import EmbeddingBase'
