# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/embedding_processed/0GeV_v3
project: ITk_1GeVSignal_MiniGNN

# Dataset parameters
pt_background_cut: 0.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [100, 5, 10] # Number of [training, validation, testing] examples
sorted_events: False
endcaps: True
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
hidden: 32
delta_eta: 1
spatial_channels: 3
cell_channels: 1
n_graph_iters: 0
nb_node_layer: 2
nb_edge_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
aggregation: sum
hidden_activation: SiLU
weight: 2
warmup: 5
lr: 0.005
factor: 0.7
patience: 15
truth_key: y
mask_background: False
max_epochs: 200